# 服务启动端口号
server:
  port: 59529
spring:
  # 服务名
  application:
    name: on-security-manage-api
  # 数据源配置
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/on_security
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

on-security:
  console:
    # 控制台服务地址
    server-address: http://127.0.0.1:59527