style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/On-Security/on-security
options:
  tag_filter_pattern: '^v'
  sort: "date"
  commits:
     filters:
       Type:
         - sparkles
         - bug
         - zap
         - recycle
         - art
         - rocket
  commit_groups:
     title_maps:
       sparkles: 新特性
       rocket: 新特性
       zap: 性能提升
       recycle: 代码重构
       art: 代码重构
       bug: Bug Fixes
  header:
    pattern: "^:(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  issues:
    prefix:
      - #
  notes:
    keywords:
      - BREAKING CHANGE