# 服务启动端口号
server:
  port: 59527
spring:
  # 服务名
  application:
    name: on-security-console-service
  # 数据源配置
  datasource:
    url: jdbc:mariadb://127.0.0.1:3308/on_security
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

on-security:
  console:
    # On-Security控制台版本号
    version: @project.version@
    # 控制台服务地址
    server-address: http://127.0.0.1:${server.port}

logging:
  level:
    org.minbox.framework.on.security.core.authorization.jdbc: debug